const constatnts = {
    FETCH_AUTHORS: 'FETCH_AUTHORS',
    POPULATE_AUTHORS: 'POPULATE_AUTHORS',
    POPULATE_AUTHORS_QUOTES: 'POPULATE_AUTHORS_QUOTES',
    POPULATE_NOUNS_QUOTES: 'POPULATE_NOUNS_QUOTES',
    POPULATE_QUOTE_BY_ID: 'POPULATE_QUOTE_BY_ID',
}

export default constatnts;
